spring.datasource.url=jdbc:mysql://localhost:3306/server_evidencija?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Zagreb
spring.datasource.username=root
spring.datasource.password=3k0p13!4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
